import type { EtfBasket, Fund, WorldState } from "../domain/model.ts";
import { accountIds, ensureAccount, postTransaction } from "../core/ledger.ts";

function moveShares(world: WorldState, securityId: string, fromId: string, toId: string, quantity: number): boolean {
  const from = world.equityHoldings.find((item) => item.ownerId === fromId && item.securityId === securityId); if (!from || from.shares < quantity) return false;
  let to = world.equityHoldings.find((item) => item.ownerId === toId && item.securityId === securityId); if (!to) { to = { id: `holding-${world.nextHoldingId++}`, securityId, ownerId: toId, shares: 0, costBasisCents: 0, dividendsReceivedCents: 0 }; world.equityHoldings.push(to); }
  const basis = Math.round(from.costBasisCents * quantity / Math.max(1, from.shares)); from.shares -= quantity; from.costBasisCents -= basis; to.shares += quantity; to.costBasisCents += basis; return true;
}
function etfFund(world: WorldState, fundId: string): Fund | null { return world.funds.find((item) => item.id === fundId && item.type === "etf" && item.unitSecurityId) ?? null; }
export function registerEtfBasket(world: WorldState, basket: EtfBasket): void { world.etfBaskets = [...world.etfBaskets.filter((item) => item.fundId !== basket.fundId), basket]; }
export function executeEtfCreation(world: WorldState, fundId: string, apId: string, creationUnits = 1): boolean {
  const fund = etfFund(world, fundId); const basket = world.etfBaskets.find((item) => item.fundId === fundId && item.authorizedParticipantIds.includes(apId)); if (!fund || !basket || creationUnits <= 0) return false;
  if (basket.components.length === 0) return false;
  const legs = basket.components.map((component) => ({ ...component, quantity: component.quantity * creationUnits })); if (legs.some((leg) => (world.equityHoldings.find((item) => item.ownerId === apId && item.securityId === leg.securityId)?.shares ?? 0) < leg.quantity)) return false;
  const transactionIds: string[] = [];
  legs.forEach((leg) => { moveShares(world, leg.securityId, apId, fund.id, leg.quantity); const value = leg.quantity * (world.listings.find((item) => item.securityId === leg.securityId)?.lastPriceCents ?? 1); const apAsset = accountIds.security(apId, leg.securityId); const fundAsset = accountIds.security(fund.id, leg.securityId); ensureAccount(world.ledger, apAsset, apId, `Актив ${leg.securityId}`, "asset", fund.currencyId); ensureAccount(world.ledger, fundAsset, fund.id, `Актив ${leg.securityId}`, "asset", fund.currencyId); transactionIds.push(postTransaction(world, "ETF_CREATION", `Передача корзины ${fund.name}`, [{ accountId: fundAsset, side: "debit", amountCents: value }, { accountId: apAsset, side: "credit", amountCents: value }], [fund.id])); }); const etfShares = basket.creationUnitSize * creationUnits;
  let holding = world.equityHoldings.find((item) => item.ownerId === apId && item.securityId === fund.unitSecurityId); if (!holding) { holding = { id: `holding-${world.nextHoldingId++}`, securityId: fund.unitSecurityId!, ownerId: apId, shares: 0, costBasisCents: 0, dividendsReceivedCents: 0 }; world.equityHoldings.push(holding); } holding.shares += etfShares;
  const nav = legs.reduce((sum, leg) => sum + leg.quantity * (world.listings.find((item) => item.securityId === leg.securityId)?.lastPriceCents ?? 0), 0); const unitAsset = accountIds.fundUnits(apId, fund.id); const unitCapital = accountIds.fundUnitCapital(fund.id); ensureAccount(world.ledger, unitAsset, apId, `Паи ${fund.name}`, "asset", fund.currencyId); ensureAccount(world.ledger, unitCapital, fund.id, "Капитал биржевого фонда", "equity", fund.currencyId); transactionIds.push(postTransaction(world, "ETF_CREATION", `Выпуск паёв ${fund.name}`, [{ accountId: unitAsset, side: "debit", amountCents: nav }, { accountId: unitCapital, side: "credit", amountCents: nav }], transactionIds));
  fund.unitsOutstandingMicros += etfShares * 1_000_000; let unitHolding = world.fundUnitHoldings.find((item) => item.fundId === fund.id && item.investorId === apId); if (!unitHolding) { unitHolding = { id: `fund-unit-${world.nextFundUnitHoldingId++}`, fundId: fund.id, investorId: apId, unitsMicros: 0, costBasisMinor: 0 }; world.fundUnitHoldings.push(unitHolding); } unitHolding.unitsMicros += etfShares * 1_000_000; unitHolding.costBasisMinor += nav; const security = world.equitySecurities.find((item) => item.id === fund.unitSecurityId); if (security) security.sharesOutstanding += etfShares;
  world.etfArbitrageEvents.push({ id: `etf-arb-${world.etfArbitrageEvents.length + 1}`, fundId, authorizedParticipantId: apId, type: "creation", units: etfShares, navMinor: nav, marketValueMinor: etfShares * (world.listings.find((item) => item.securityId === fund.unitSecurityId)?.lastPriceCents ?? 0), costsMinor: 0, transactionIds, elapsedMonth: world.clock.elapsedMonths }); return true;
}
export function executeEtfRedemption(world: WorldState, fundId: string, apId: string, creationUnits = 1): boolean {
  if (creationUnits <= 0) return false;
  const fund = etfFund(world, fundId); const basket = world.etfBaskets.find((item) => item.fundId === fundId && item.authorizedParticipantIds.includes(apId)); if (!fund || !basket || !fund.unitSecurityId) return false; const etfShares = basket.creationUnitSize * creationUnits;
  if (basket.components.length === 0) return false;
  const units = world.equityHoldings.find((item) => item.ownerId === apId && item.securityId === fund.unitSecurityId); if (!units || units.shares < etfShares || basket.components.some((component) => (world.equityHoldings.find((item) => item.ownerId === fund.id && item.securityId === component.securityId)?.shares ?? 0) < component.quantity * creationUnits)) return false;
  const nav = basket.components.reduce((sum, component) => sum + component.quantity * creationUnits * (world.listings.find((item) => item.securityId === component.securityId)?.lastPriceCents ?? 0), 0); const transactionIds: string[] = []; const unitAsset = accountIds.fundUnits(apId, fund.id); const unitCapital = accountIds.fundUnitCapital(fund.id); transactionIds.push(postTransaction(world, "ETF_REDEMPTION", `Погашение паёв ${fund.name}`, [{ accountId: unitCapital, side: "debit", amountCents: nav }, { accountId: unitAsset, side: "credit", amountCents: nav }], [fund.id]));
  units.shares -= etfShares; for (const component of basket.components) { const quantity = component.quantity * creationUnits; moveShares(world, component.securityId, fund.id, apId, quantity); const value = quantity * (world.listings.find((item) => item.securityId === component.securityId)?.lastPriceCents ?? 1); transactionIds.push(postTransaction(world, "ETF_REDEMPTION", `Возврат корзины ${fund.name}`, [{ accountId: accountIds.security(apId, component.securityId), side: "debit", amountCents: value }, { accountId: accountIds.security(fund.id, component.securityId), side: "credit", amountCents: value }], transactionIds)); } const unitHolding = world.fundUnitHoldings.find((item) => item.fundId === fund.id && item.investorId === apId); if (unitHolding) { unitHolding.unitsMicros -= etfShares * 1_000_000; unitHolding.costBasisMinor = Math.max(0, unitHolding.costBasisMinor - nav); } fund.unitsOutstandingMicros -= etfShares * 1_000_000; const security = world.equitySecurities.find((item) => item.id === fund.unitSecurityId); if (security) security.sharesOutstanding -= etfShares;
  world.etfArbitrageEvents.push({ id: `etf-arb-${world.etfArbitrageEvents.length + 1}`, fundId, authorizedParticipantId: apId, type: "redemption", units: etfShares, navMinor: nav, marketValueMinor: etfShares * (world.listings.find((item) => item.securityId === fund.unitSecurityId)?.lastPriceCents ?? 0), costsMinor: 0, transactionIds, elapsedMonth: world.clock.elapsedMonths }); return true;
}
export function runEtfArbitrage(world: WorldState): void {
  for (const basket of world.etfBaskets) { const fund = etfFund(world, basket.fundId); const listing = fund?.unitSecurityId && world.listings.find((item) => item.securityId === fund.unitSecurityId); if (!fund || !listing) continue; const basketNav = basket.components.reduce((sum, component) => sum + component.quantity * (world.listings.find((item) => item.securityId === component.securityId)?.lastPriceCents ?? 0), 0) / Math.max(1, basket.creationUnitSize); const gapBps = (listing.lastPriceCents - basketNav) * 10_000 / Math.max(1, basketNav); const ap = basket.authorizedParticipantIds[0]; if (gapBps > 80) executeEtfCreation(world, fund.id, ap); else if (gapBps < -80) executeEtfRedemption(world, fund.id, ap); }
}
