import { accountIds, ensureAccount, postTransaction } from "../core/ledger.ts";
import { companyValuation, executeShareBuyback } from "../corporate/finance.ts";
import type { GovernanceProposal, RestructuringCase, WorldState } from "../domain/model.ts";

export function submitGovernanceProposal(world: WorldState, companyId: string, proposerId: string, type: GovernanceProposal["type"], requestedAmountMinor = 0): GovernanceProposal | null {
  const company = world.companies.find((item) => item.id === companyId); const security = company && world.equitySecurities.find((item) => item.id === company.equitySecurityId); const holding = security && world.equityHoldings.find((item) => item.securityId === security.id && item.ownerId === proposerId);
  if (!company || !security || !holding || holding.shares * 10_000 / Math.max(1, security.sharesOutstanding) < 300) return null;
  const proposal: GovernanceProposal = { id: `governance-${world.governanceProposals.length + 1}`, companyId, proposerId, type, requestedAmountMinor, votesFor: 0, votesAgainst: 0, status: "proposed", createdAtMonth: world.clock.elapsedMonths }; world.governanceProposals.push(proposal); return proposal;
}
export function voteGovernanceProposal(world: WorldState, proposalId: string): GovernanceProposal | null {
  const proposal = world.governanceProposals.find((item) => item.id === proposalId && item.status === "proposed"); const company = proposal && world.companies.find((item) => item.id === proposal.companyId); const security = company && world.equitySecurities.find((item) => item.id === company.equitySecurityId); if (!proposal || !company || !security) return null;
  for (const holding of world.equityHoldings.filter((item) => item.securityId === security.id && item.shares > 0)) { const supports = proposal.type === "buyback" ? company.retainedEarningsCents > proposal.requestedAmountMinor : proposal.type === "company-sale" ? company.distressMonths > 1 : true; if (supports) proposal.votesFor += holding.shares; else proposal.votesAgainst += holding.shares; }
  proposal.status = proposal.votesFor * 10_000 / Math.max(1, security.sharesOutstanding) >= 5_001 ? "approved" : "rejected"; return proposal;
}
export function executeGovernanceProposal(world: WorldState, proposalId: string): boolean {
  const proposal = world.governanceProposals.find((item) => item.id === proposalId && item.status === "approved"); const company = proposal && world.companies.find((item) => item.id === proposal.companyId); if (!proposal || !company) return false;
  if (proposal.type === "buyback") { const security = world.equitySecurities.find((item) => item.id === company.equitySecurityId)!; const seller = world.equityHoldings.filter((item) => item.securityId === security.id && item.ownerId !== company.id && item.shares > 0).sort((a, b) => b.shares - a.shares)[0]; const price = world.listings.find((item) => item.securityId === security.id)?.lastPriceCents ?? 1; if (!seller || !executeShareBuyback(world, company.id, seller.ownerId, Math.min(seller.shares, Math.floor(proposal.requestedAmountMinor / price)), price).ok) return false; }
  proposal.status = "executed"; return true;
}
export function openRestructuringCase(world: WorldState, companyId: string): RestructuringCase | null {
  const company = world.companies.find((item) => item.id === companyId); if (!company) return null; const goingConcern = companyValuation(world, company.id).enterpriseValueCents; const liquidation = Math.round((company.productiveCapital.bookValueCents + company.inventoryValueCents) * 0.55); const creditors = world.loans.filter((item) => item.borrowerId === company.id && item.status === "active").map((item) => item.lenderBankId); const item: RestructuringCase = { id: `restructure-${world.restructuringCases.length + 1}`, companyId, goingConcernValueMinor: goingConcern, liquidationValueMinor: liquidation, status: goingConcern > liquidation ? "negotiating" : "liquidation", haircutBps: 0, debtToEquityMinor: 0, creditorIds: [...new Set(creditors)], openedAtMonth: world.clock.elapsedMonths }; world.restructuringCases.push(item); return item;
}
export function executeDebtToEquity(world: WorldState, caseId: string, conversionBps = 4_000, haircutBps = 1_000): boolean {
  const item = world.restructuringCases.find((entry) => entry.id === caseId && entry.status === "negotiating"); const company = item && world.companies.find((entry) => entry.id === item.companyId); const security = company && world.equitySecurities.find((entry) => entry.id === company.equitySecurityId); if (!item || !company || !security) return false; let converted = 0;
  for (const loan of world.loans.filter((entry) => entry.borrowerId === company.id && entry.status === "active")) {
    const haircut = Math.round(loan.remainingPrincipalCents * haircutBps / 10_000); const conversion = Math.round((loan.remainingPrincipalCents - haircut) * conversionBps / 10_000); const reduction = haircut + conversion; if (reduction <= 0) continue; loan.remainingPrincipalCents -= reduction;
    const price = Math.max(1, Math.round(companyValuation(world, company.id).equityValueCents / Math.max(1, security.sharesOutstanding))); const shares = Math.max(1, Math.floor(conversion / price)); security.sharesOutstanding += shares; let holding = world.equityHoldings.find((entry) => entry.securityId === security.id && entry.ownerId === loan.lenderBankId); if (!holding) { holding = { id: `holding-${world.nextHoldingId++}`, securityId: security.id, ownerId: loan.lenderBankId, shares: 0, costBasisCents: 0, dividendsReceivedCents: 0 }; world.equityHoldings.push(holding); } holding.shares += shares; holding.costBasisCents += conversion;
    const liability = accountIds.loanLiability(company.id, loan.lenderBankId); const bankLoan = accountIds.bankLoanAsset(loan.lenderBankId, company.id); const bankSecurity = accountIds.security(loan.lenderBankId, security.id); const equity = accountIds.contributedEquity(company.id); const gain = accountIds.operatingIncome(company.id); ensureAccount(world.ledger, bankSecurity, loan.lenderBankId, "Акции после реструктуризации", "asset", loan.currencyId); ensureAccount(world.ledger, equity, company.id, "Капитал после реструктуризации", "equity", loan.currencyId); ensureAccount(world.ledger, gain, company.id, "Доход от списания долга", "income", loan.currencyId);
    postTransaction(world, "LOAN_DEFAULT", `Debt-to-equity ${item.id}`, [{ accountId: liability, side: "debit", amountCents: reduction }, { accountId: equity, side: "credit", amountCents: conversion }, { accountId: gain, side: "credit", amountCents: haircut }, { accountId: accountIds.bankCreditLoss(loan.lenderBankId), side: "debit", amountCents: haircut }, { accountId: bankLoan, side: "credit", amountCents: reduction }, { accountId: bankSecurity, side: "debit", amountCents: conversion }], [item.id]); converted += conversion;
  }
  item.haircutBps = haircutBps; item.debtToEquityMinor = converted; item.status = converted > 0 ? "restructured" : "failed"; return converted > 0;
}
